langfuse:
  chat_trace_name: FunctionCallChat
  function_trace_name: LLMChat
  host: https://cloud.langfuse.com
  public_key:
  secret_key:
  user_id: tian_chat
llm:
  openai:
    api_key:
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model: qwen-plus
rag:
  embedding:
    choose: default
    default:
      cache_dir: D:\LLM
      model: BAAI/bge-large-zh-v1.5
    openai:
      api_key: ''
      base_url: ''
      model: ''
  input_dir: ../docs
  rerank:
    choose: default
    cohere:
      api_key: ''
      model: ''
    default:
      cache_dir: D:\LLM
      model: BAAI/bge-reranker-large
tool:
  delivery:
    api_key:
    base_url: https://qyexpress.market.alicloudapi.com/composite/queryexpress
  google:
    api_key:
  weather:
    api_key:
    base_url: https://restapi.amap.com/v3/weather/weatherInfo?parameters

use_captcha: True