langfuse:
  chat_trace_name: "FunctionCallChat"
  function_trace_name: "LLMChat"
  host: "https://cloud.langfuse.com"
  public_key:
  secret_key:
  user_id: "tian_chat"

openai:
  api_key:
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model_name: "qwen-plus"

embedding:
  api_key: ""
  base_url: ""
  model_name: ""

rerank:
  api_key: ""
  model_name: ""
  base_url: ""

tool_delivery:
  api_key: ""
  base_url: "https://qyexpress.market.alicloudapi.com/composite/queryexpress"

tool_google:
  api_key: ""

tool_weather:
  api_key: ""
  base_url: "https://restapi.amap.com/v3/weather/weatherInfo?parameters"

use_captcha: True