langfuse:
  chat_trace_name: FunctionCallChat
  function_trace_name: LLMChat
  host: https://cloud.langfuse.com
  public_key: pk-lf-5742f8fa-50aa-4ac8-bace-8d1a04e25257
  secret_key: sk-lf-9c5b4119-3a2b-4554-91e6-f8fd1ea1cd72
  user_id: tian_chat
llm:
  openai:
    api_key: 填入你自己的API key，在这里可换deepseek、kimi等模型
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model: qwen-plus
rag:
  embedding:
    choose: default
    default:
      cache_dir: D:\LLM
      model: BAAI/bge-large-zh-v1.5
    openai:
      api_key: ''
      base_url: ''
      model: ''
  input_dir: ../docs
  rerank:
    choose: default
    cohere:
      api_key: ''
      model: ''
    default:
      cache_dir: D:\LLM
      model: BAAI/bge-reranker-large
tool:
  delivery:
    api_key: df695c94fc644d27b23c760bf425de21
    base_url: https://qyexpress.market.alicloudapi.com/composite/queryexpress
  google:
    api_key: cdc3b207606843b4c883849c3a0f833c13057811bea964bef192707d8845f3d8
  weather:
    api_key: fac0ad465078da96a3ec6ba1ccc6746f
    base_url: https://restapi.amap.com/v3/weather/weatherInfo?parameters

# 这几个API KEY免费提供给大家
